### ISSUE TITLE
Update banner component to use fixed background image

### ISSUE THREAD

**Issue by lucasvianav** [sa-sel/site-bixos-2022#16]
## Task description

The image should scroll along the page

Depends on #17 

Example snippet:
```html
<div class="about my-5 w-100 d-flex justify-content-center align-items-center">
    <div class="container d-inline-block text-justify m-5 p-5 text text-white">
        <h1 class="title pb-4 text-justify w-75">Quem somos nós?</h1>
        <p *ngFor="let paragraph of bodyParagraphs">{{ paragraph }}<br/></p>
    </div>
</div>
```

```css
.about {
    background-image: url("./glassy-blur-image.png");
    background-repeat: no-repeat;
    background-position: center center;
    background-attachment: fixed;
    background-size: cover;
    background-clip: border-box;
    background-color: $blue;
}

.text {
    width: 90%;
    border: 2px solid $white;
}


@include media-breakpoint-up(md) {
    .text {
        width: 35%;
    }
}

@include media-breakpoint-up(sm) {
    .text {
        width: 55%;
    }
}
```
